Craco => next.js
navikt/ditt-sykefravaer pull request #70
Opened 2022-01-05 13:27 UTC by kjarbr

2022-01-06 06:55 UTC, heyvard requested changes

2022-01-06 06:55 UTC, heyvard commented on next.config.js
> +    },
her er det masse ting som ikke bruker i denne appen. Tenker det kan fjernes enn så lenge

2022-01-06 12:04 UTC, kjarbr commented on next.config.js
> +    },
Det er fjernet

2022-01-07 11:50 UTC, heyvard approved these changes

2022-01-07 11:56 UTC, merged